# Generated by Django 4.1.1 on 2022-09-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0076_modellogentry_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanoramaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "panorama_id",
                    models.CharField(
                        default="",
                        help_text="Panorama ID of the tour panorama from Google Street View",
                        max_length=255,
                        verbose_name="Panorama ID",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        help_text="Co-ordinates of the tour panorama",
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "lng",
                    models.FloatField(
                        help_text="Co-ordinates of the tour panorama",
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        help_text="Direction of the tour panorama",
                        verbose_name="Heading",
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        help_text="POV of the tour panorama",
                        verbose_name="Panorama View Elevation",
                    ),
                ),
                (
                    "zoom_level",
                    models.FloatField(
                        default=1,
                        help_text="Zoom level of the tour panorama",
                        verbose_name="Zoom Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Tour Panorama",
                "verbose_name_plural": "Virtual Tour Panoramas",
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TourPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "maps_url",
                    models.TextField(
                        help_text="Paste in the url of the Google Maps page. The values below will then be parsed from the URL.",
                        verbose_name="Google Maps URL",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "lng",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "heading",
                    models.FloatField(blank=True, null=True, verbose_name="Heading"),
                ),
                (
                    "elevation",
                    models.FloatField(blank=True, null=True, verbose_name="Pitch"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
