# Generated by Django 4.1.1 on 2022-09-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="panoramapage",
            options={},
        ),
    ]
