# Generated by Django 4.1.1 on 2022-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_tours", "0002_alter_panoramapage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpage",
            name="zoom_level",
            field=models.FloatField(
                default=1,
                help_text="Zoom level of the tour panorama",
                verbose_name="Zoom Level",
            ),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="maps_url",
            field=models.TextField(),
        ),
    ]
