# Generated by Django 4.1.1 on 2022-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_tours", "0003_tourpage_zoom_level_alter_tourpage_maps_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panoramapage",
            name="elevation",
            field=models.FloatField(verbose_name="Elevation/Pitch"),
        ),
        migrations.AlterField(
            model_name="panoramapage",
            name="heading",
            field=models.FloatField(verbose_name="Direction/Rotation"),
        ),
        migrations.AlterField(
            model_name="panoramapage",
            name="lat",
            field=models.FloatField(verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="panoramapage",
            name="lng",
            field=models.FloatField(verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="panoramapage",
            name="panorama_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="panoramapage",
            name="zoom_level",
            field=models.FloatField(verbose_name="Zoom In/Out"),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="elevation",
            field=models.FloatField(verbose_name="Elevation/Pitch"),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="heading",
            field=models.FloatField(verbose_name="Direction/Rotation"),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="lat",
            field=models.FloatField(verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="lng",
            field=models.FloatField(verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="maps_url",
            field=models.TextField(
                help_text="Copy a Google Maps Street View URL and paste it here. It's values will be used as a starting point for the first panorama.",
                verbose_name="Google Maps Street View URL",
            ),
        ),
        migrations.AlterField(
            model_name="tourpage",
            name="zoom_level",
            field=models.FloatField(verbose_name="Zoom In/Out"),
        ),
    ]
