# Generated by Django 4.1.1 on 2022-09-18 16:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("virtual_tours", "0004_alter_panoramapage_elevation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panoramapage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
