# Generated by Django 4.1.2 on 2022-10-23 16:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0077_alter_revision_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PanoramaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("panorama_id", models.CharField(max_length=255)),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("lng", models.FloatField(verbose_name="Longitude")),
                ("heading", models.FloatField(verbose_name="Direction/Rotation")),
                ("elevation", models.FloatField(verbose_name="Elevation/Pitch")),
                ("zoom_level", models.FloatField(verbose_name="Zoom In/Out")),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Panorama",
                "verbose_name_plural": "Panoramas",
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TourPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "maps_url",
                    models.TextField(
                        help_text="Copy a Google Maps Street View URL and paste it here.\n        It's values will be used as a starting point for the first panorama.",  # noqa: E501
                        verbose_name="Google Maps Street View URL",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("lng", models.FloatField(verbose_name="Longitude")),
                ("heading", models.FloatField(verbose_name="Direction/Rotation")),
                ("elevation", models.FloatField(verbose_name="Elevation/Pitch")),
                ("zoom_level", models.FloatField(verbose_name="Zoom In/Out")),
            ],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
