# Generated by Django 4.1.7 on 2023-02-17 16:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("test_testapp", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanoramaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("panorama_id", models.CharField(max_length=255)),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("lng", models.FloatField(verbose_name="Longitude")),
                ("heading", models.FloatField(verbose_name="Direction/Rotation")),
                ("elevation", models.FloatField(verbose_name="Elevation/Pitch")),
                ("zoom_level", models.FloatField(verbose_name="Zoom In/Out")),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TourPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "maps_url",
                    models.TextField(
                        help_text=(
                            "Copy a Google Maps Street View URL and paste it here.",
                            "\n",
                            "It's values will be used as a starting point for the first panorama.",
                        ),
                        verbose_name="Google Maps Street View URL",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("lng", models.FloatField(verbose_name="Longitude")),
                ("heading", models.FloatField(verbose_name="Direction/Rotation")),
                ("elevation", models.FloatField(verbose_name="Elevation/Pitch")),
                ("zoom_level", models.FloatField(verbose_name="Zoom In/Out")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
